sources:
  - name: Fake API
    handler:
      jsonSchema:
        baseUrl: http://localhost:3000
        operationHeaders:
          Content-Type: application/json
        operations:
          - type: Query
            field: me
            path: /me
            method: GET
            responseSchema: ./json-schemas/user.json
          - type: Mutation
            field: createUser
            path: /users
            method: POST
            requestSchema: ./json-schemas/userInput.json
            responseSchema: ./json-schemas/user.json
    transforms:
      - namingConvention:
          fieldNames: camelCase
